application: gae-google
version: 1
runtime: go
api_version: go1.8
handlers:
- url: /.*
  script: _go_app
  secure: always
env_variables:
  AUTH_GOOGLE_CLIENT_ID: "xxx"
  AUTH_GOOGLE_CLIENT_SECRET: "xxx"
  AUTH_GOOGLE_REDIRECT_URL: "http://localhost:8080/auth/google/callback"
